avoid <<= operator, now deprecated in sbt
scala/community-builds pull request #361
Opened 2016-10-20 22:32 UTC by SethTisue

smoothing the way to upgrading the build to sbt 0.13.13 when
it comes out

review by @dwijnand

2016-10-20 22:35 UTC, SethTisue commented
test run https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/830/consoleFull (404 til Jenkins gets off the drugs and high on life)

2016-10-20 23:07 UTC, dwijnand requested changes
Also, give it a quick 1-project run-through, just to check the macro doesn't throw a fit..

2016-10-20 23:07 UTC, dwijnand commented on community.dbuild
> +    val redefined = scopes.map(scope => scalacOptions in scope ~= (_.map(fn)))
no it needs to be something like `scalacOptions in scope ~= fn`

2016-10-20 23:10 UTC, SethTisue commented
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/832/consoleFull

2016-10-20 23:13 UTC, dwijnand approved these changes

2016-10-21 14:59 UTC, SethTisue commented
the spire error looks unrelated to me

2016-10-21 14:59 UTC, merged